# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://chaodongyang.com/
date_format: "ordinal"
title: Android开发社区
subtitle: "学习改变人生"
description: "东洋的个人博客"
keywords: Android开发社区, Android, Java, React Native ,C/C++
favicon: /new_favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: 东洋
organization: 
organization_url: https://chaodongyang.com/
github_username: chaodongyang
location: Shanghai, China
email: 1184259921@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: chaodongyang/chaodongyang.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: chaodongyang
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: chaodongyang
    repo: chaodongyang.github.io
    oauth:
        client_id: 69da8c2cdb18361285c3
        client_secret: 8a83bd8a7a5aa3f73916c7937f4de97726201990
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: chaodongyang
    repo: chaodongyang.github.io
    clientID: ce06a78586c48efbb98c
    clientSecret: b61130a2d4494d29f43618c47749456ed61950b1
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-108914115-1
